### ISSUE TITLE
A good scraper will find the value.

### ISSUE THREAD

**Issue by GeorgeRay** [bell-kevin/chap11pursue#21]
This is not a good solution. A good scraper will find this value and put it in the form.
<input type="hidden" name="captcha_image" value="<?php echo $captcha_image; ?>">

**Comment by bell-kevin** [comment]
How do I fix it?

**Comment by GeorgeRay** [comment]
Use a database to save the captcha attempts.

Use a session variable:
https://stackoverflow.com/questions/11633229/singleton-pattern-in-php-how-can-i-save-state-between-requests
________________________________

**Comment by bell-kevin** [comment]
Ah! This assignment was chapter 11, and chapter 12 is all about cookies and sessions!
